
version: '3.9'

services:
  node-app:
    image: node:24
    container_name: api_mockup
    working_dir: /usr/src/app
    volumes:
           - .:/usr/src/app
    ports:
      - "3000:3000"
    command: bash -c "npm install && npx --yes nodemon -L --exec npm start"
    restart: always